### ISSUE TITLE
Instructions for Ubuntu?

### ISSUE THREAD

**Issue by jikkuatwork** [neetly/figma-agent-linux#134]
I just installed the script and it seems to have installed without issues. Also, I have the service started:

```
➜ journalctl --user-unit figma-agent.service
Dec 22 01:23:42 wonderland systemd[2093]: Starting figma-agent.service - Figma Agent for Linux...
Dec 22 01:23:42 wonderland systemd[2093]: Started figma-agent.service - Figma Agent for Linux.
Dec 22 01:23:42 wonderland figma-agent[361211]: [2023-12-21T19:53:42Z INFO  actix_server::builder] Starting 1 workers
Dec 22 01:23:42 wonderland figma-agent[361211]: [2023-12-21T19:53:42Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
```

I was expecting to find the installed fonts in Ubuntu show up in search in Figma's browser version in Ubuntu. Am I misunderstanding something? Is there anything more I should do to get this working?

**Comment by fan87** [comment]
I had the same issue, I checked the network tab, and see if it's blocked
![image](https://github.com/neetly/figma-agent-linux/assets/75163822/6a43170a-78f8-4c48-a686-605c780b0597)

And it turns out it's actually my Brave Shield blocking the request:
![image](https://github.com/neetly/figma-agent-linux/assets/75163822/7349fc66-69b9-4b7f-ac0e-4201f231fb38)
![image](https://github.com/neetly/figma-agent-linux/assets/75163822/a17997f4-5a90-4492-92f7-97ca073ffdaa)


If it still doesn't work, try this command to see if the server is still responding:
```sh
curl --header "Origin: https://www.figma.com" "http://127.0.0.1:18412/figma/font-files"
```
